services:
  db:
    image: mysql:8.0
    container_name: mindspace_db
    restart: always
    env_file:
      - ./backend/.env
    environment:
      MYSQL_ROOT_PASSWORD: root_password_v1
      MYSQL_DATABASE: mindspace_db
      MYSQL_USER: mindspace_user
      MYSQL_PASSWORD: mindspace_password_v1
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot_password_v1" ]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    container_name: mindspace_backend
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    env_file:
      - ./backend/.env
    command: sh -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"

    depends_on:
      db:
        condition: service_healthy

volumes:
  mysql_data:
