"""create_reflections_table

Revision ID: 8d31a8f417cd
Revises: cc27e6389932
Create Date: 2026-07-02 19:43:28.223940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d31a8f417cd'
down_revision = 'cc27e6389932'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_reflections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('journal_id', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('detected_patterns', sa.Text(), nullable=False),
    sa.Column('reflection_question', sa.Text(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('model_used', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['journal_id'], ['journal_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_reflections_id'), 'ai_reflections', ['id'], unique=False)
    op.create_index(op.f('ix_ai_reflections_journal_id'), 'ai_reflections', ['journal_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_reflections_journal_id'), table_name='ai_reflections')
    op.drop_index(op.f('ix_ai_reflections_id'), table_name='ai_reflections')
    op.drop_table('ai_reflections')
    # ### end Alembic commands ###
