"""add_performance_indices

Revision ID: cfb7c10b7541
Revises: 9a58b8f219ff
Create Date: 2026-07-03 16:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfb7c10b7541'
down_revision = '9a58b8f219ff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_journal_entries_created_at', 'journal_entries', ['created_at'], unique=False)
    op.create_index('ix_journal_entries_user_deleted', 'journal_entries', ['user_id', 'deleted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_journal_entries_user_deleted', table_name='journal_entries')
    op.drop_index('ix_journal_entries_created_at', table_name='journal_entries')
    # ### end Alembic commands ###
